# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='正文内容必须为Markdown格式', verbose_name='正文'),
        ),
    ]
